<?php
/**
 * Infinity Theme Functions
 *
 * @package Infinity
 * @since 1.0.0
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Theme version
define('INFINITY_VERSION', '4.0.0');

// Theme directory paths
define('INFINITY_DIR', get_template_directory());
define('INFINITY_URI', get_template_directory_uri());

/**
 * Theme Setup
 */
function infinity_theme_setup() {
    // Make theme available for translation
    load_theme_textdomain('infinity', INFINITY_DIR . '/languages');

    // Add default posts and comments RSS feed links to head
    add_theme_support('automatic-feed-links');

    // Let WordPress manage the document title
    add_theme_support('title-tag');

    // Enable support for Post Thumbnails
    add_theme_support('post-thumbnails');

    // Add support for responsive embedded content
    add_theme_support('responsive-embeds');

    // Add support for HTML5 markup
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ));

    // Add support for custom logo
    add_theme_support('custom-logo', array(
        'height'      => 100,
        'width'       => 400,
        'flex-width'  => true,
        'flex-height' => true,
    ));

    // Add support for selective refresh for widgets
    add_theme_support('customize-selective-refresh-widgets');

    // Register navigation menus
    register_nav_menus(array(
        'primary' => esc_html__('Primary Menu', 'infinity'),
        'footer'  => esc_html__('Footer Menu', 'infinity'),
    ));
}
add_action('after_setup_theme', 'infinity_theme_setup');

/**
 * Enqueue Scripts and Styles
 */
function infinity_enqueue_scripts() {
    // Main stylesheet
    wp_enqueue_style('infinity-style', get_stylesheet_uri(), array(), INFINITY_VERSION);

    // Orbitron display face for headings and the wordmark
    wp_enqueue_style(
        'infinity-orbitron',
        'https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700;900&display=swap',
        array(),
        null
    );

    /*
     * The React app (~270 KB JS + 38 KB CSS) only mounts on templates
     * that render #infinity-root: the posts-page fallback (index.php)
     * and the Parker's App Shell page template. Content pages skip it
     * entirely.
     */
    $load_app = (is_home() && !is_front_page()) || is_page_template('template-app.php');
    $load_app = apply_filters('infinity_load_app', $load_app);
    if (!$load_app) {
        // Comment reply script still needed on posts
        if (is_singular() && comments_open() && get_option('thread_comments')) {
            wp_enqueue_script('comment-reply');
        }
        return;
    }

    // React app styles (will be generated by Vite/Next.js)
    if (file_exists(INFINITY_DIR . '/frontend/dist/style.css')) {
        wp_enqueue_style(
            'infinity-app-styles',
            INFINITY_URI . '/frontend/dist/style.css',
            array('infinity-style'),
            INFINITY_VERSION
        );
    }

    // React app scripts (will be generated by Vite/Next.js)
    if (file_exists(INFINITY_DIR . '/frontend/dist/main.js')) {
        wp_enqueue_script(
            'infinity-app',
            INFINITY_URI . '/frontend/dist/main.js',
            array(),
            INFINITY_VERSION,
            true
        );
    }

    // Pass PHP data to JavaScript
    $frontend_data = array(
        'restUrl'        => esc_url_raw(rest_url()),
        'nonce'          => wp_create_nonce('wp_rest'),
        'graphqlUrl'     => esc_url_raw(home_url('/graphql')),
        'siteUrl'        => esc_url_raw(home_url('/')),
        'siteName'       => get_bloginfo('name'),
        'themePath'      => INFINITY_URI,
        'steamUrl'       => esc_url_raw(get_option('infinity_steam_url', 'https://store.steampowered.com/app/4094340/Explore_the_Universe_2175/')),
        'steamLabel'     => get_option('infinity_steam_label', 'Explore the Universe'),
        'currentUserId'  => get_current_user_id(),
        'isUserLoggedIn' => is_user_logged_in(),
        'theme'          => get_option('infinity_theme_mode', 'dark-cosmic'),
        'stripeKey'      => get_option('infinity_stripe_publishable_key', ''),
        'stripe'         => array(
            'enabled'        => infinity_stripe_configured(),
            'publishableKey' => get_option('infinity_stripe_publishable_key', ''),
            'prices'         => array(
                'monthly' => get_option('infinity_stripe_price_monthly', ''),
                'yearly'  => get_option('infinity_stripe_price_yearly', ''),
            ),
            'premiumPrice'   => infinity_get_premium_price(),
        ),
    );

    // Add user subscription data if logged in
    if (is_user_logged_in()) {
        $user_id = get_current_user_id();
        $frontend_data['subscription'] = array(
            'status'            => infinity_get_user_subscription_status($user_id),
            'isPremium'         => infinity_has_active_subscription($user_id),
            'currentPeriodEnd'  => (int) get_user_meta($user_id, 'infinity_subscription_current_period_end', true),
            'cancelAtPeriodEnd' => get_user_meta($user_id, 'infinity_subscription_cancel_at_period_end', true) === '1',
        );
    }

    // Allow filtering of frontend data
    $frontend_data = apply_filters('infinity_frontend_data', $frontend_data);

    wp_localize_script('infinity-app', 'infinityData', $frontend_data);

    // Comment reply script
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }
}
add_action('wp_enqueue_scripts', 'infinity_enqueue_scripts');

/**
 * Load the Vite-built app bundle as an ES module
 *
 * The build emits ES module output (export statements, dynamic imports),
 * which fails with a SyntaxError when loaded via a classic script tag.
 */
function infinity_module_script_loader_tag($tag, $handle, $src) {
    if ('infinity-app' === $handle) {
        $tag = sprintf(
            '<script type="module" src="%s" id="%s-js"></script>' . "\n",
            esc_url($src),
            esc_attr($handle)
        );
    }
    return $tag;
}
add_filter('script_loader_tag', 'infinity_module_script_loader_tag', 10, 3);

/**
 * Resource hints: preconnect to the Steam CDN on the front page,
 * where the game's key art is loaded from it.
 */
function infinity_resource_hints($urls, $relation_type) {
    if ('preconnect' === $relation_type) {
        $urls[] = array('href' => 'https://fonts.googleapis.com');
        $urls[] = array('href' => 'https://fonts.gstatic.com', 'crossorigin');
        if (is_front_page()) {
            $urls[] = array(
                'href' => 'https://shared.akamai.steamstatic.com',
                'crossorigin',
            );
        }
    }
    return $urls;
}
add_filter('wp_resource_hints', 'infinity_resource_hints', 10, 2);

/**
 * Register Custom Post Types
 */
function infinity_register_post_types() {
    // Simulations Post Type
    register_post_type('simulation', array(
        'labels' => array(
            'name'                  => esc_html__('Simulations', 'infinity'),
            'singular_name'         => esc_html__('Simulation', 'infinity'),
            'menu_name'             => esc_html__('Simulations', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Simulation', 'infinity'),
            'edit_item'             => esc_html__('Edit Simulation', 'infinity'),
            'new_item'              => esc_html__('New Simulation', 'infinity'),
            'view_item'             => esc_html__('View Simulation', 'infinity'),
            'search_items'          => esc_html__('Search Simulations', 'infinity'),
            'not_found'             => esc_html__('No simulations found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No simulations found in trash', 'infinity'),
            'all_items'             => esc_html__('All Simulations', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'simulation',
        'graphql_plural_name' => 'simulations',
        'menu_icon'           => 'dashicons-admin-site-alt3',
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt', 'author', 'comments'),
        'rewrite'             => array('slug' => 'simulations'),
        'capability_type'     => 'post',
    ));

    // Blueprints Post Type (User-created simulation configs)
    register_post_type('blueprint', array(
        'labels' => array(
            'name'                  => esc_html__('Blueprints', 'infinity'),
            'singular_name'         => esc_html__('Blueprint', 'infinity'),
            'menu_name'             => esc_html__('Blueprints', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Blueprint', 'infinity'),
            'edit_item'             => esc_html__('Edit Blueprint', 'infinity'),
            'new_item'              => esc_html__('New Blueprint', 'infinity'),
            'view_item'             => esc_html__('View Blueprint', 'infinity'),
            'search_items'          => esc_html__('Search Blueprints', 'infinity'),
            'not_found'             => esc_html__('No blueprints found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No blueprints found in trash', 'infinity'),
            'all_items'             => esc_html__('All Blueprints', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'blueprint',
        'graphql_plural_name' => 'blueprints',
        'menu_icon'           => 'dashicons-editor-code',
        'supports'            => array('title', 'editor', 'thumbnail', 'author', 'comments'),
        'rewrite'             => array('slug' => 'blueprints'),
        'capability_type'     => 'post',
    ));

    // Challenges Post Type
    register_post_type('challenge', array(
        'labels' => array(
            'name'                  => esc_html__('Challenges', 'infinity'),
            'singular_name'         => esc_html__('Challenge', 'infinity'),
            'menu_name'             => esc_html__('Challenges', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Challenge', 'infinity'),
            'edit_item'             => esc_html__('Edit Challenge', 'infinity'),
            'new_item'              => esc_html__('New Challenge', 'infinity'),
            'view_item'             => esc_html__('View Challenge', 'infinity'),
            'search_items'          => esc_html__('Search Challenges', 'infinity'),
            'not_found'             => esc_html__('No challenges found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No challenges found in trash', 'infinity'),
            'all_items'             => esc_html__('All Challenges', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'challenge',
        'graphql_plural_name' => 'challenges',
        'menu_icon'           => 'dashicons-awards',
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite'             => array('slug' => 'challenges'),
        'capability_type'     => 'post',
    ));
}
add_action('init', 'infinity_register_post_types');

/**
 * Register Custom Taxonomies
 */
function infinity_register_taxonomies() {
    // Simulation Categories
    register_taxonomy('simulation_category', 'simulation', array(
        'labels' => array(
            'name'              => esc_html__('Simulation Categories', 'infinity'),
            'singular_name'     => esc_html__('Simulation Category', 'infinity'),
            'search_items'      => esc_html__('Search Categories', 'infinity'),
            'all_items'         => esc_html__('All Categories', 'infinity'),
            'edit_item'         => esc_html__('Edit Category', 'infinity'),
            'update_item'       => esc_html__('Update Category', 'infinity'),
            'add_new_item'      => esc_html__('Add New Category', 'infinity'),
            'new_item_name'     => esc_html__('New Category Name', 'infinity'),
            'menu_name'         => esc_html__('Categories', 'infinity'),
        ),
        'hierarchical'        => true,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'simulationCategory',
        'graphql_plural_name' => 'simulationCategories',
        'rewrite'             => array('slug' => 'simulation-category'),
    ));

    // Difficulty Level
    register_taxonomy('difficulty_level', array('simulation', 'challenge'), array(
        'labels' => array(
            'name'              => esc_html__('Difficulty Levels', 'infinity'),
            'singular_name'     => esc_html__('Difficulty Level', 'infinity'),
            'search_items'      => esc_html__('Search Levels', 'infinity'),
            'all_items'         => esc_html__('All Levels', 'infinity'),
            'edit_item'         => esc_html__('Edit Level', 'infinity'),
            'update_item'       => esc_html__('Update Level', 'infinity'),
            'add_new_item'      => esc_html__('Add New Level', 'infinity'),
            'new_item_name'     => esc_html__('New Level Name', 'infinity'),
            'menu_name'         => esc_html__('Difficulty', 'infinity'),
        ),
        'hierarchical'        => false,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'difficultyLevel',
        'graphql_plural_name' => 'difficultyLevels',
        'rewrite'             => array('slug' => 'difficulty'),
    ));

    // Physics Engine Tag
    register_taxonomy('physics_engine', 'simulation', array(
        'labels' => array(
            'name'              => esc_html__('Physics Engines', 'infinity'),
            'singular_name'     => esc_html__('Physics Engine', 'infinity'),
            'search_items'      => esc_html__('Search Engines', 'infinity'),
            'all_items'         => esc_html__('All Engines', 'infinity'),
            'edit_item'         => esc_html__('Edit Engine', 'infinity'),
            'update_item'       => esc_html__('Update Engine', 'infinity'),
            'add_new_item'      => esc_html__('Add New Engine', 'infinity'),
            'new_item_name'     => esc_html__('New Engine Name', 'infinity'),
            'menu_name'         => esc_html__('Physics Engines', 'infinity'),
        ),
        'hierarchical'        => false,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'physicsEngine',
        'graphql_plural_name' => 'physicsEngines',
        'rewrite'             => array('slug' => 'physics-engine'),
    ));
}
add_action('init', 'infinity_register_taxonomies');

/**
 * Add Custom Image Sizes
 */
function infinity_custom_image_sizes() {
    add_image_size('simulation-thumbnail', 400, 300, true);
    add_image_size('simulation-hero', 1200, 600, true);
    add_image_size('blueprint-preview', 600, 400, true);
}
add_action('after_setup_theme', 'infinity_custom_image_sizes');

/**
 * Register Widget Areas
 */
function infinity_widgets_init() {
    register_sidebar(array(
        'name'          => esc_html__('Sidebar', 'infinity'),
        'id'            => 'sidebar-1',
        'description'   => esc_html__('Add widgets here to appear in your sidebar.', 'infinity'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h2 class="widget-title">',
        'after_title'   => '</h2>',
    ));

    register_sidebar(array(
        'name'          => esc_html__('Footer', 'infinity'),
        'id'            => 'footer-1',
        'description'   => esc_html__('Add widgets here to appear in your footer.', 'infinity'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h2 class="widget-title">',
        'after_title'   => '</h2>',
    ));
}
add_action('widgets_init', 'infinity_widgets_init');

/**
 * Add Theme Customizer Settings
 */
function infinity_customize_register($wp_customize) {
    // Theme Mode Section
    $wp_customize->add_section('infinity_theme_mode', array(
        'title'    => esc_html__('Theme Appearance', 'infinity'),
        'priority' => 30,
    ));

    $wp_customize->add_setting('infinity_theme_mode', array(
        'type'              => 'option',
        'default'           => 'dark-cosmic',
        'sanitize_callback' => 'infinity_sanitize_theme_mode',
        'transport'         => 'refresh',
    ));

    $wp_customize->add_control('infinity_theme_mode', array(
        'label'   => esc_html__('Visual Theme', 'infinity'),
        'section' => 'infinity_theme_mode',
        'type'    => 'select',
        'choices' => array(
            'dark-cosmic'    => esc_html__('Dark Cosmic', 'infinity'),
            'light-playful'  => esc_html__('Light Playful', 'infinity'),
            'science-light'  => esc_html__('Science Mode (Light)', 'infinity'),
            'science-dark'   => esc_html__('Science Mode (Dark)', 'infinity'),
        ),
    ));

    // Stripe Settings Section
    $wp_customize->add_section('infinity_stripe_settings', array(
        'title'    => esc_html__('Subscription Settings', 'infinity'),
        'priority' => 40,
    ));

    $wp_customize->add_setting('infinity_stripe_publishable_key', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_publishable_key', array(
        'label'       => esc_html__('Stripe Publishable Key', 'infinity'),
        'description' => esc_html__('Enter your Stripe publishable key for subscriptions', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'text',
    ));

    // Stripe Secret Key (stored securely)
    $wp_customize->add_setting('infinity_stripe_secret_key', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_secret_key', array(
        'label'       => esc_html__('Stripe Secret Key', 'infinity'),
        'description' => esc_html__('Enter your Stripe secret key (starts with sk_)', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'password',
    ));

    // Stripe Webhook Secret
    $wp_customize->add_setting('infinity_stripe_webhook_secret', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_webhook_secret', array(
        'label'       => esc_html__('Stripe Webhook Secret', 'infinity'),
        'description' => esc_html__('Enter your Stripe webhook signing secret (starts with whsec_)', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'password',
    ));

    // Premium Pricing
    $wp_customize->add_setting('infinity_premium_price', array(
        'type'              => 'option',
        'default'           => '20',
        'sanitize_callback' => 'absint',
    ));

    $wp_customize->add_control('infinity_premium_price', array(
        'label'       => esc_html__('Premium Monthly Price (USD)', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'number',
        'input_attrs' => array(
            'min'  => 1,
            'max'  => 1000,
            'step' => 1,
        ),
    ));

    // Stripe Price IDs
    $wp_customize->add_setting('infinity_stripe_price_monthly', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_price_monthly', array(
        'label'       => esc_html__('Stripe Monthly Price ID', 'infinity'),
        'description' => esc_html__('Price ID from Stripe dashboard (starts with price_)', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'text',
    ));

    $wp_customize->add_setting('infinity_stripe_price_yearly', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_price_yearly', array(
        'label'       => esc_html__('Stripe Yearly Price ID', 'infinity'),
        'description' => esc_html__('Yearly price ID from Stripe dashboard', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'text',
    ));

    // Steam Promotion Section
    $wp_customize->add_section('infinity_steam_settings', array(
        'title'       => esc_html__('Steam Promotion', 'infinity'),
        'description' => esc_html__('Settings for the Explore the Universe Steam call-to-action shown in the header and home page.', 'infinity'),
        'priority'    => 35,
    ));

    $wp_customize->add_setting('infinity_steam_url', array(
        'type'              => 'option',
        'default'           => 'https://store.steampowered.com/app/4094340/Explore_the_Universe_2175/',
        'sanitize_callback' => 'esc_url_raw',
    ));

    $wp_customize->add_control('infinity_steam_url', array(
        'label'       => esc_html__('Steam Store URL', 'infinity'),
        'description' => esc_html__('Full URL to your Steam store page (e.g. https://store.steampowered.com/app/...)', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'url',
    ));

    $wp_customize->add_setting('infinity_steam_label', array(
        'type'              => 'option',
        'default'           => 'Explore the Universe',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_steam_label', array(
        'label'       => esc_html__('Game Title', 'infinity'),
        'description' => esc_html__('Shown on the Steam buttons and the featured card', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'text',
    ));

    $wp_customize->add_setting('infinity_etu_site_url', array(
        'type'              => 'option',
        'default'           => 'https://exploretheuniverse2175.com',
        'sanitize_callback' => 'esc_url_raw',
    ));

    $wp_customize->add_control('infinity_etu_site_url', array(
        'label'       => esc_html__('Explore the Universe 2175 site URL', 'infinity'),
        'description' => esc_html__('The game\'s own site, where players sign up', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'url',
    ));

    $wp_customize->add_setting('infinity_parkers_url', array(
        'type'              => 'option',
        'default'           => 'https://parkersphysics.com',
        'sanitize_callback' => 'esc_url_raw',
    ));

    $wp_customize->add_control('infinity_parkers_url', array(
        'label'       => esc_html__('Parker\'s Physics URL', 'infinity'),
        'description' => esc_html__('The live simulation sandbox', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'url',
    ));

    // Property logos (fall back to each site's favicon when empty)
    $logo_fields = array(
        'infinity_parkers_logo'     => __('Parker\'s Physics logo', 'infinity'),
        'infinity_etu_logo'         => __('Explore the Universe 2175 logo', 'infinity'),
        'infinity_landscaping_logo' => __('Telford Landscaping logo', 'infinity'),
    );
    foreach ($logo_fields as $logo_id => $logo_label) {
        $wp_customize->add_setting($logo_id, array(
            'type'              => 'option',
            'default'           => '',
            'sanitize_callback' => 'esc_url_raw',
        ));
        $wp_customize->add_control(new WP_Customize_Image_Control($wp_customize, $logo_id, array(
            'label'   => $logo_label,
            'section' => 'infinity_steam_settings',
        )));
    }

    $wp_customize->add_setting('infinity_etu_embed', array(
        'type'              => 'option',
        'default'           => 0,
        'sanitize_callback' => 'absint',
    ));

    $wp_customize->add_setting('infinity_etu_band_art', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'esc_url_raw',
    ));

    $wp_customize->add_control(new WP_Customize_Image_Control($wp_customize, 'infinity_etu_band_art', array(
        'label'       => esc_html__('Official ETU 2175 key art', 'infinity'),
        'description' => esc_html__('Shown in the game band and preview card. Leave empty to pull from Steam (with a bundled fallback).', 'infinity'),
        'section'     => 'infinity_steam_settings',
    )));

    $wp_customize->add_setting('infinity_etu_video', array(
        'type'              => 'option',
        'default'           => '',
        'sanitize_callback' => 'esc_url_raw',
    ));

    $wp_customize->add_control('infinity_etu_video', array(
        'label'       => esc_html__('ETU teaser video URL', 'infinity'),
        'description' => esc_html__('Leave empty to auto-detect the newest ETU_Vid* video in your media library.', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'url',
    ));

    $wp_customize->add_control('infinity_etu_embed', array(
        'label'       => esc_html__('Live-embed ExploreTheUniverse2175.com on the homepage', 'infinity'),
        'description' => esc_html__('Enable only after that site allows framing (frame-ancestors https://elliottelford.com). Until then its card shows the Steam key art.', 'infinity'),
        'section'     => 'infinity_steam_settings',
        'type'        => 'checkbox',
    ));
}
add_action('customize_register', 'infinity_customize_register');

/**
 * Sanitize theme mode setting
 */
function infinity_sanitize_theme_mode($input) {
    $valid_modes = array('dark-cosmic', 'light-playful', 'science-light', 'science-dark');
    return in_array($input, $valid_modes, true) ? $input : 'dark-cosmic';
}

/**
 * Add theme mode to body class
 */
function infinity_body_classes($classes) {
    $theme_mode = get_option('infinity_theme_mode', 'dark-cosmic');
    $classes[] = 'theme-' . $theme_mode;

    if (is_user_logged_in()) {
        $classes[] = 'user-logged-in';
    }

    return $classes;
}
add_filter('body_class', 'infinity_body_classes');

/**
 * Add theme mode data attribute to body
 */
function infinity_add_theme_attribute() {
    $theme_mode = get_option('infinity_theme_mode', 'dark-cosmic');
    echo ' data-theme="' . esc_attr($theme_mode) . '"';
}
add_action('body_open', 'infinity_add_theme_attribute');

/**
 * Include additional files
 */
require_once INFINITY_DIR . '/inc/user-roles.php';
require_once INFINITY_DIR . '/inc/subscription-functions.php';
require_once INFINITY_DIR . '/inc/simulation-meta.php';
require_once INFINITY_DIR . '/inc/api-endpoints.php';
require_once INFINITY_DIR . '/inc/stripe-api.php';
require_once INFINITY_DIR . '/inc/analytics-dashboard.php';
require_once INFINITY_DIR . '/inc/property-promos.php';
require_once INFINITY_DIR . '/inc/subscribe.php';
require_once INFINITY_DIR . '/inc/icons.php';

// Load WooCommerce compatibility if plugin is active
if (class_exists('WooCommerce')) {
    require_once INFINITY_DIR . '/inc/woocommerce-integration.php';
}

// Load WPGraphQL extensions if plugin is active
if (function_exists('graphql')) {
    require_once INFINITY_DIR . '/inc/graphql-extensions.php';
}

/**
 * Breadcrumb Navigation
 *
 * Displays breadcrumb navigation for improved UX and SEO.
 *
 * @since 1.0.0
 */
function infinity_breadcrumbs() {
    // Don't show on front page
    if (is_front_page()) {
        return;
    }

    $separator = '<span class="breadcrumb-separator" aria-hidden="true">/</span>';
    $home_title = __('Home', 'infinity');

    echo '<nav class="breadcrumbs" aria-label="' . esc_attr__('Breadcrumb', 'infinity') . '">';
    echo '<div class="container">';
    echo '<ol class="breadcrumb-list" itemscope itemtype="https://schema.org/BreadcrumbList">';

    // Home link
    echo '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
    echo '<a href="' . esc_url(home_url('/')) . '" itemprop="item"><span itemprop="name">' . esc_html($home_title) . '</span></a>';
    echo '<meta itemprop="position" content="1" />';
    echo '</li>';

    $position = 2;

    if (is_archive()) {
        echo $separator;

        if (is_post_type_archive()) {
            $post_type = get_queried_object();
            echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
            echo '<span itemprop="name" aria-current="page">' . esc_html($post_type->label) . '</span>';
            echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
            echo '</li>';
        } elseif (is_category() || is_tag() || is_tax()) {
            $term = get_queried_object();

            // Show post type archive link for custom taxonomies
            if (is_tax()) {
                $taxonomy = get_taxonomy($term->taxonomy);
                if (!empty($taxonomy->object_type)) {
                    $post_type = get_post_type_object($taxonomy->object_type[0]);
                    if ($post_type && $post_type->has_archive) {
                        echo '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
                        echo '<a href="' . esc_url(get_post_type_archive_link($taxonomy->object_type[0])) . '" itemprop="item">';
                        echo '<span itemprop="name">' . esc_html($post_type->label) . '</span></a>';
                        echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
                        echo '</li>';
                        echo $separator;
                        $position++;
                    }
                }
            }

            echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
            echo '<span itemprop="name" aria-current="page">' . esc_html($term->name) . '</span>';
            echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
            echo '</li>';
        } elseif (is_date()) {
            if (is_year()) {
                echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
                echo '<span itemprop="name" aria-current="page">' . esc_html(get_the_date('Y')) . '</span>';
                echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
                echo '</li>';
            } elseif (is_month()) {
                echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
                echo '<span itemprop="name" aria-current="page">' . esc_html(get_the_date('F Y')) . '</span>';
                echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
                echo '</li>';
            } elseif (is_day()) {
                echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
                echo '<span itemprop="name" aria-current="page">' . esc_html(get_the_date()) . '</span>';
                echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
                echo '</li>';
            }
        } elseif (is_author()) {
            echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
            echo '<span itemprop="name" aria-current="page">' . esc_html(get_the_author()) . '</span>';
            echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
            echo '</li>';
        }
    } elseif (is_singular()) {
        echo $separator;

        $post_type = get_post_type();
        $post_type_obj = get_post_type_object($post_type);

        // Show post type archive link
        if ($post_type !== 'page' && $post_type_obj && $post_type_obj->has_archive) {
            echo '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
            echo '<a href="' . esc_url(get_post_type_archive_link($post_type)) . '" itemprop="item">';
            echo '<span itemprop="name">' . esc_html($post_type_obj->label) . '</span></a>';
            echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
            echo '</li>';
            echo $separator;
            $position++;
        }

        // Show parent page hierarchy for pages
        if (is_page()) {
            $ancestors = array_reverse(get_post_ancestors(get_the_ID()));
            foreach ($ancestors as $ancestor_id) {
                echo '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
                echo '<a href="' . esc_url(get_permalink($ancestor_id)) . '" itemprop="item">';
                echo '<span itemprop="name">' . esc_html(get_the_title($ancestor_id)) . '</span></a>';
                echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
                echo '</li>';
                echo $separator;
                $position++;
            }
        }

        // Current page
        echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
        echo '<span itemprop="name" aria-current="page">' . esc_html(get_the_title()) . '</span>';
        echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
        echo '</li>';

    } elseif (is_search()) {
        echo $separator;
        echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
        /* translators: %s: search query */
        echo '<span itemprop="name" aria-current="page">' . sprintf(esc_html__('Search: %s', 'infinity'), get_search_query()) . '</span>';
        echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
        echo '</li>';

    } elseif (is_404()) {
        echo $separator;
        echo '<li class="breadcrumb-item breadcrumb-current" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">';
        echo '<span itemprop="name" aria-current="page">' . esc_html__('Page Not Found', 'infinity') . '</span>';
        echo '<meta itemprop="position" content="' . esc_attr($position) . '" />';
        echo '</li>';
    }

    echo '</ol>';
    echo '</div>';
    echo '</nav>';
}

/**
 * Enqueue Navigation Scripts
 *
 * @since 1.0.0
 */
function infinity_enqueue_navigation_scripts() {
    wp_enqueue_script(
        'infinity-navigation',
        INFINITY_URI . '/assets/js/navigation.js',
        array(),
        INFINITY_VERSION,
        true
    );

    wp_enqueue_script(
        'infinity-subscribe',
        INFINITY_URI . '/assets/js/subscribe.js',
        array(),
        INFINITY_VERSION,
        true
    );

    // 12-particle 3D orbit swarm around the header logo (site-wide)
    wp_enqueue_script(
        'infinity-logo-orbits',
        INFINITY_URI . '/assets/js/logo-orbits.js',
        array(),
        INFINITY_VERSION,
        true
    );

    // Light/dark toggle (initial mode is set pre-paint in wp_head)
    wp_enqueue_script(
        'infinity-theme-toggle',
        INFINITY_URI . '/assets/js/theme-toggle.js',
        array(),
        INFINITY_VERSION,
        true
    );

    // Pass settings to JavaScript
    wp_localize_script('infinity-navigation', 'infinityNav', array(
        'stickyHeader'   => get_theme_mod('infinity_sticky_header', false),
        'backToTopText'  => __('Back to top', 'infinity'),
    ));

    // Black hole accretion disk shader, front page hero only
    if (is_front_page()) {
        wp_enqueue_script(
            'infinity-blackhole',
            INFINITY_URI . '/assets/js/blackhole.js',
            array(),
            INFINITY_VERSION,
            true
        );
        wp_enqueue_script(
            'infinity-property-previews',
            INFINITY_URI . '/assets/js/property-previews.js',
            array(),
            INFINITY_VERSION,
            true
        );
        wp_enqueue_script(
            'infinity-tag-globe',
            INFINITY_URI . '/assets/js/tag-globe.js',
            array(),
            INFINITY_VERSION,
            true
        );
        wp_enqueue_script(
            'infinity-steam-fit',
            INFINITY_URI . '/assets/js/steam-fit.js',
            array(),
            INFINITY_VERSION,
            true
        );
    }
}
add_action('wp_enqueue_scripts', 'infinity_enqueue_navigation_scripts');

/**
 * Pick light or dark before first paint. A stored visitor preference
 * wins; otherwise the visitor's clock decides (07:00-18:59 = light).
 * The Customizer theme mode still chooses WHICH light and dark skins
 * are used. Runs at wp_head priority 0 so no flash of wrong theme.
 */
function infinity_theme_mode_boot() {
    $base  = get_option('infinity_theme_mode', 'dark-cosmic');
    $dark  = ('science-dark' === $base) ? 'science-dark' : 'dark-cosmic';
    $light = ('light-playful' === $base) ? 'light-playful' : 'science-light';
    ?>
    <script>
    (function () {
        window.infinityThemeCfg = { dark: '<?php echo esc_js($dark); ?>', light: '<?php echo esc_js($light); ?>' };
        var mode = null;
        try { mode = localStorage.getItem('infinityTheme'); } catch (e) {}
        if (mode !== 'light' && mode !== 'dark') {
            var h = new Date().getHours();
            mode = (h >= 7 && h < 19) ? 'light' : 'dark';
        }
        var d = document.documentElement;
        d.setAttribute('data-theme', mode === 'light' ? window.infinityThemeCfg.light : window.infinityThemeCfg.dark);
        d.setAttribute('data-mode', mode);
    })();
    </script>
    <?php
}
add_action('wp_head', 'infinity_theme_mode_boot', 0);

/**
 * Add Navigation Customizer Settings
 *
 * @since 1.0.0
 */
function infinity_navigation_customize_register($wp_customize) {
    // Navigation Section
    $wp_customize->add_section('infinity_navigation', array(
        'title'    => esc_html__('Navigation & UX', 'infinity'),
        'priority' => 35,
    ));

    // Sticky Header Option
    $wp_customize->add_setting('infinity_sticky_header', array(
        'default'           => false,
        'sanitize_callback' => 'rest_sanitize_boolean',
        'transport'         => 'refresh',
    ));

    $wp_customize->add_control('infinity_sticky_header', array(
        'label'       => esc_html__('Enable Sticky Header', 'infinity'),
        'description' => esc_html__('Header will remain fixed at the top while scrolling.', 'infinity'),
        'section'     => 'infinity_navigation',
        'type'        => 'checkbox',
    ));

    // Show Breadcrumbs Option
    $wp_customize->add_setting('infinity_show_breadcrumbs', array(
        'default'           => true,
        'sanitize_callback' => 'rest_sanitize_boolean',
        'transport'         => 'refresh',
    ));

    $wp_customize->add_control('infinity_show_breadcrumbs', array(
        'label'       => esc_html__('Show Breadcrumbs', 'infinity'),
        'description' => esc_html__('Display breadcrumb navigation on inner pages.', 'infinity'),
        'section'     => 'infinity_navigation',
        'type'        => 'checkbox',
    ));

    // Back to Top Option
    $wp_customize->add_setting('infinity_show_back_to_top', array(
        'default'           => true,
        'sanitize_callback' => 'rest_sanitize_boolean',
        'transport'         => 'refresh',
    ));

    $wp_customize->add_control('infinity_show_back_to_top', array(
        'label'       => esc_html__('Show Back to Top Button', 'infinity'),
        'description' => esc_html__('Display a button to scroll back to the top.', 'infinity'),
        'section'     => 'infinity_navigation',
        'type'        => 'checkbox',
    ));
}
add_action('customize_register', 'infinity_navigation_customize_register');

/**
 * Conditionally hide back-to-top button via body class
 *
 * @since 1.0.0
 */
function infinity_navigation_body_classes($classes) {
    if (!get_theme_mod('infinity_show_back_to_top', true)) {
        $classes[] = 'hide-back-to-top';
    }
    return $classes;
}
add_filter('body_class', 'infinity_navigation_body_classes');

/* ==========================================================================
   Front Page Content & SEO
   ========================================================================== */

/**
 * Query recent posts from a comma-separated list of category slugs.
 *
 * Only slugs that exist as categories are used; if none match, falls
 * back to recent posts so homepage sections never render empty on a
 * site whose category names differ.
 */
function infinity_fp_query($slugs_csv, $count = 3, $exclude = array(), $rotate = false) {
    $slugs = array_filter(array_map('trim', explode(',', (string) $slugs_csv)));
    $existing = array();

    foreach ($slugs as $slug) {
        if (get_category_by_slug($slug)) {
            $existing[] = $slug;
        }
    }

    $args = array(
        'post_type'           => 'post',
        'posts_per_page'      => (int) $count,
        'ignore_sticky_posts' => true,
    );

    if ($existing) {
        $args['category_name'] = implode(',', $existing);
    }

    if ($exclude) {
        $args['post__not_in'] = array_map('intval', $exclude);
    }

    /*
     * Rotation: walk the category's full archive over time so every
     * article gets homepage exposure. The offset advances by one
     * card-row per hour and wraps; hourly steps play nicely with
     * full-page caches (each cache period shows a different set).
     */
    if ($rotate && $existing) {
        $ckey  = 'inf_fp_total_' . md5(implode(',', $existing));
        $total = get_transient($ckey);
        if (false === $total) {
            $count_q = new WP_Query(array(
                'post_type'      => 'post',
                'category_name'  => implode(',', $existing),
                'posts_per_page' => 1,
                'fields'         => 'ids',
            ));
            $total = (int) $count_q->found_posts;
            set_transient($ckey, $total, HOUR_IN_SECONDS);
        }
        if ($total > $count) {
            $step           = (int) floor(time() / HOUR_IN_SECONDS);
            $args['offset'] = ($step * (int) $count) % $total;
        }
    }

    $query = new WP_Query($args);

    // Wrap around the end of the archive so rows are always full
    if ($rotate && !empty($args['offset']) && $query->post_count < (int) $count) {
        $have  = wp_list_pluck($query->posts, 'ID');
        $again = $args;
        unset($again['offset']);
        $again['posts_per_page'] = (int) $count - $query->post_count;
        $again['post__not_in']   = array_map('intval', array_merge($exclude, $have));
        $wrap = new WP_Query($again);
        $query->posts      = array_merge($query->posts, $wrap->posts);
        $query->post_count = count($query->posts);
    }

    return $query;
}

/**
 * Get the archive link for the first existing category in a slug list.
 */
function infinity_fp_first_category_link($slugs_csv) {
    $slugs = array_filter(array_map('trim', explode(',', (string) $slugs_csv)));

    foreach ($slugs as $slug) {
        $cat = get_category_by_slug($slug);
        if ($cat) {
            return get_category_link($cat);
        }
    }

    return '';
}

/**
 * Homepage Content customizer settings
 */
function infinity_front_page_customize_register($wp_customize) {
    $wp_customize->add_section('infinity_front_page', array(
        'title'       => esc_html__('Homepage Content', 'infinity'),
        'description' => esc_html__('Controls the sections of the front page. Category lists are comma-separated slugs; the first slugs that exist on your site are used.', 'infinity'),
        'priority'    => 32,
    ));

    $fields = array(
        'infinity_featured_post_id' => array(
            'label'       => esc_html__('Featured Post ID', 'infinity'),
            'description' => esc_html__('Post ID to feature at the top (e.g. the mushroom article). Leave 0 for the most recent post.', 'infinity'),
            'default'     => 0,
            'sanitize'    => 'absint',
            'type'        => 'number',
        ),
        'infinity_pillar_health_slugs' => array(
            'label'       => esc_html__('Health & Anatomy categories', 'infinity'),
            'description' => esc_html__('Comma-separated category slugs', 'infinity'),
            'default'     => 'anatomy,osteology,health,nutrition,fitness,medicine,wellness,body',
            'sanitize'    => 'sanitize_text_field',
            'type'        => 'text',
        ),
        'infinity_pillar_science_slugs' => array(
            'label'       => esc_html__('Science categories', 'infinity'),
            'description' => esc_html__('Comma-separated category slugs', 'infinity'),
            'default'     => 'science,biology,nature,technology,research,mushrooms,fungi,discovery',
            'sanitize'    => 'sanitize_text_field',
            'type'        => 'text',
        ),
        'infinity_pillar_travel_slugs' => array(
            'label'       => esc_html__('Travel categories', 'infinity'),
            'description' => esc_html__('Comma-separated category slugs', 'infinity'),
            'default'     => 'travel,experiences,adventures,journeys,field-notes,life,blog',
            'sanitize'    => 'sanitize_text_field',
            'type'        => 'text',
        ),
        'infinity_pillar_space_slugs' => array(
            'label'       => esc_html__('Space & Simulations categories', 'infinity'),
            'description' => esc_html__('Comma-separated category slugs', 'infinity'),
            'default'     => 'space,astronomy,astrophysics,simulations,physics,cosmos,universe,satellites,black-holes',
            'sanitize'    => 'sanitize_text_field',
            'type'        => 'text',
        ),
        'infinity_pillar_mind_slugs' => array(
            'label'       => esc_html__('Mind & Philosophy categories', 'infinity'),
            'description' => esc_html__('Comma-separated category slugs', 'infinity'),
            'default'     => 'philosophy,religion,buddhism,hinduism,yoga,mind,meditation,spirituality,psychology',
            'sanitize'    => 'sanitize_text_field',
            'type'        => 'text',
        ),
        'infinity_landscaping_url' => array(
            'label'       => esc_html__('Landscaping site URL', 'infinity'),
            'description' => '',
            'default'     => 'https://telfordlandscaping.com',
            'sanitize'    => 'esc_url_raw',
            'type'        => 'url',
        ),
        'infinity_parkers_features' => array(
            'label'       => esc_html__("Parker's Physics highlights", 'infinity'),
            'description' => esc_html__('One per line: Emoji|Label|Description|URL. Empty = built-in defaults.', 'infinity'),
            'default'     => '',
            'sanitize'    => 'sanitize_textarea_field',
            'type'        => 'textarea',
        ),
        'infinity_landscaping_features' => array(
            'label'       => esc_html__('Telford Landscaping highlights', 'infinity'),
            'description' => esc_html__('One per line: Emoji|Label|Description|URL. Empty = built-in defaults.', 'infinity'),
            'default'     => '',
            'sanitize'    => 'sanitize_textarea_field',
            'type'        => 'textarea',
        ),
    );

    foreach ($fields as $id => $field) {
        $wp_customize->add_setting($id, array(
            'type'              => 'option',
            'default'           => $field['default'],
            'sanitize_callback' => $field['sanitize'],
        ));
        $wp_customize->add_control($id, array(
            'label'       => $field['label'],
            'description' => $field['description'],
            'section'     => 'infinity_front_page',
            'type'        => $field['type'],
        ));
    }
}
add_action('customize_register', 'infinity_front_page_customize_register');

/**
 * Basic SEO tags: meta description, Open Graph, Twitter card.
 *
 * Skipped automatically when a dedicated SEO plugin (Yoast, Rank Math,
 * All in One SEO) is active so we never emit duplicate tags.
 */
function infinity_seo_meta_tags() {
    if (defined('WPSEO_VERSION') || class_exists('RankMath') || defined('AIOSEO_VERSION')) {
        return;
    }

    $title = wp_get_document_title();

    if (is_front_page()) {
        $description = get_bloginfo('description');
        $url         = home_url('/');
        $image       = get_template_directory_uri() . '/screenshot.png';
        $type        = 'website';
    } elseif (is_singular()) {
        $description = get_the_excerpt() ? wp_trim_words(get_the_excerpt(), 30) : get_bloginfo('description');
        $url         = get_permalink();
        $image       = get_the_post_thumbnail_url(null, 'large') ?: get_template_directory_uri() . '/screenshot.png';
        $type        = 'article';
    } else {
        return;
    }

    printf('<meta name="description" content="%s">' . "\n", esc_attr($description));
    printf('<meta property="og:title" content="%s">' . "\n", esc_attr($title));
    printf('<meta property="og:description" content="%s">' . "\n", esc_attr($description));
    printf('<meta property="og:url" content="%s">' . "\n", esc_url($url));
    printf('<meta property="og:type" content="%s">' . "\n", esc_attr($type));
    printf('<meta property="og:site_name" content="%s">' . "\n", esc_attr(get_bloginfo('name')));
    printf('<meta property="og:image" content="%s">' . "\n", esc_url($image));
    printf('<meta property="og:locale" content="%s">' . "\n", esc_attr(get_locale()));
    if (is_singular('post')) {
        printf('<meta property="article:published_time" content="%s">' . "\n", esc_attr(get_the_date('c')));
        printf('<meta property="article:modified_time" content="%s">' . "\n", esc_attr(get_the_modified_date('c')));
    }
    echo '<meta name="twitter:card" content="summary_large_image">' . "\n";
}
add_action('wp_head', 'infinity_seo_meta_tags', 5);

/**
 * JSON-LD structured data: WebSite + Person on the front page,
 * Article on single posts. Skipped when an SEO plugin is active.
 */
function infinity_seo_json_ld() {
    if (defined('WPSEO_VERSION') || class_exists('RankMath') || defined('AIOSEO_VERSION')) {
        return;
    }

    $schema = array();

    if (is_front_page()) {
        $schema[] = array(
            '@context'        => 'https://schema.org',
            '@type'           => 'WebSite',
            'name'            => get_bloginfo('name'),
            'url'             => home_url('/'),
            'description'     => get_bloginfo('description'),
            'potentialAction' => array(
                '@type'       => 'SearchAction',
                'target'      => home_url('/?s={search_term_string}'),
                'query-input' => 'required name=search_term_string',
            ),
        );
        $schema[] = array(
            '@context' => 'https://schema.org',
            '@type'    => 'Person',
            'name'     => 'Elliot Telford',
            'url'      => home_url('/'),
            'sameAs'   => array_filter(array(
                get_option('infinity_steam_url', ''),
                get_option('infinity_landscaping_url', 'https://telfordlandscaping.com'),
            )),
        );
    } elseif (is_singular('post')) {
        $schema[] = array(
            '@context'      => 'https://schema.org',
            '@type'         => 'Article',
            'headline'      => get_the_title(),
            'datePublished' => get_the_date('c'),
            'dateModified'  => get_the_modified_date('c'),
            'author'        => array(
                '@type' => 'Person',
                'name'  => get_the_author(),
            ),
            'image'         => get_the_post_thumbnail_url(null, 'large') ?: '',
            'mainEntityOfPage' => get_permalink(),
        );
    }

    foreach ($schema as $item) {
        printf(
            '<script type="application/ld+json">%s</script>' . "\n",
            wp_json_encode($item, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
        );
    }
}
add_action('wp_head', 'infinity_seo_json_ld', 6);

/**
 * Point crawlers at the core XML sitemap (/wp-sitemap.xml).
 */
function infinity_robots_txt($output, $public) {
    if ($public) {
        $output .= "\nSitemap: " . esc_url(home_url('/wp-sitemap.xml')) . "\n";
    }
    return $output;
}
add_filter('robots_txt', 'infinity_robots_txt', 10, 2);

/**
 * Canonical URLs for non-singular views (core only covers singular).
 */
function infinity_canonical_tag() {
    if (defined('WPSEO_VERSION') || class_exists('RankMath') || defined('AIOSEO_VERSION')) {
        return;
    }
    if (is_singular()) {
        return; // core handles it
    }
    $canonical = '';
    if (is_front_page()) {
        $canonical = home_url('/');
    } elseif (is_home()) {
        $canonical = get_permalink(get_option('page_for_posts'));
    } elseif (is_category() || is_tag() || is_tax()) {
        $canonical = get_term_link(get_queried_object());
    } elseif (is_post_type_archive()) {
        $canonical = get_post_type_archive_link(get_query_var('post_type'));
    }
    if ($canonical && !is_wp_error($canonical)) {
        printf('<link rel="canonical" href="%s">' . "\n", esc_url($canonical));
    }
}
add_action('wp_head', 'infinity_canonical_tag', 4);

/**
 * BreadcrumbList structured data on single posts.
 */
function infinity_breadcrumb_json_ld() {
    if (defined('WPSEO_VERSION') || class_exists('RankMath') || defined('AIOSEO_VERSION')) {
        return;
    }
    if (!is_singular('post')) {
        return;
    }
    $items = array(array(
        '@type'    => 'ListItem',
        'position' => 1,
        'name'     => get_bloginfo('name'),
        'item'     => home_url('/'),
    ));
    $cats = get_the_category();
    if ($cats) {
        $items[] = array(
            '@type'    => 'ListItem',
            'position' => 2,
            'name'     => $cats[0]->name,
            'item'     => get_category_link($cats[0]),
        );
    }
    $items[] = array(
        '@type'    => 'ListItem',
        'position' => count($items) + 1,
        'name'     => get_the_title(),
        'item'     => get_permalink(),
    );
    printf(
        '<script type="application/ld+json">%s</script>' . "\n",
        wp_json_encode(array(
            '@context'        => 'https://schema.org',
            '@type'           => 'BreadcrumbList',
            'itemListElement' => $items,
        ), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
    );
}
add_action('wp_head', 'infinity_breadcrumb_json_ld', 7);

/**
 * Indexing hygiene: keep thin/duplicate views out of the index.
 *
 * GSC showed ~3,850 duplicate URLs. Attachment pages, date/author
 * archives, and search results are the classic sources: noindex the
 * archives, disable attachment pages entirely (redirecting old ones
 * to their file), and let canonicals cover the rest.
 */
function infinity_wp_robots($robots) {
    if (is_date() || is_author() || is_search() || is_attachment()) {
        $robots['noindex'] = true;
        $robots['follow']  = true;
    }
    return $robots;
}
add_filter('wp_robots', 'infinity_wp_robots');

// WP 6.4+: stop generating attachment pages at all
add_filter('wp_attachment_pages_enabled', '__return_false');

// Legacy attachment URLs redirect to the file itself
function infinity_attachment_redirect() {
    if (is_attachment()) {
        $url = wp_get_attachment_url(get_queried_object_id());
        if ($url) {
            wp_safe_redirect($url, 301);
            exit;
        }
    }
}
add_action('template_redirect', 'infinity_attachment_redirect');
