<?php
/**
 * Infinity Theme Functions
 *
 * @package Infinity
 * @since 1.0.0
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Theme version
define('INFINITY_VERSION', '1.0.0');

// Theme directory paths
define('INFINITY_DIR', get_template_directory());
define('INFINITY_URI', get_template_directory_uri());

/**
 * Theme Setup
 */
function infinity_theme_setup() {
    // Make theme available for translation
    load_theme_textdomain('infinity', INFINITY_DIR . '/languages');

    // Add default posts and comments RSS feed links to head
    add_theme_support('automatic-feed-links');

    // Let WordPress manage the document title
    add_theme_support('title-tag');

    // Enable support for Post Thumbnails
    add_theme_support('post-thumbnails');

    // Add support for responsive embedded content
    add_theme_support('responsive-embeds');

    // Add support for HTML5 markup
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ));

    // Add support for custom logo
    add_theme_support('custom-logo', array(
        'height'      => 100,
        'width'       => 400,
        'flex-width'  => true,
        'flex-height' => true,
    ));

    // Add support for selective refresh for widgets
    add_theme_support('customize-selective-refresh-widgets');

    // Register navigation menus
    register_nav_menus(array(
        'primary' => esc_html__('Primary Menu', 'infinity'),
        'footer'  => esc_html__('Footer Menu', 'infinity'),
    ));
}
add_action('after_setup_theme', 'infinity_theme_setup');

/**
 * Enqueue Scripts and Styles
 */
function infinity_enqueue_scripts() {
    // Main stylesheet
    wp_enqueue_style('infinity-style', get_stylesheet_uri(), array(), INFINITY_VERSION);

    // React app styles (will be generated by Vite/Next.js)
    if (file_exists(INFINITY_DIR . '/frontend/dist/style.css')) {
        wp_enqueue_style(
            'infinity-app-styles',
            INFINITY_URI . '/frontend/dist/style.css',
            array('infinity-style'),
            INFINITY_VERSION
        );
    }

    // React app scripts (will be generated by Vite/Next.js)
    if (file_exists(INFINITY_DIR . '/frontend/dist/main.js')) {
        wp_enqueue_script(
            'infinity-app',
            INFINITY_URI . '/frontend/dist/main.js',
            array(),
            INFINITY_VERSION,
            true
        );
    }

    // Pass PHP data to JavaScript
    wp_localize_script('infinity-app', 'infinityData', array(
        'restUrl'        => esc_url_raw(rest_url()),
        'nonce'          => wp_create_nonce('wp_rest'),
        'graphqlUrl'     => esc_url_raw(home_url('/graphql')),
        'siteUrl'        => esc_url_raw(home_url('/')),
        'themePath'      => INFINITY_URI,
        'currentUserId'  => get_current_user_id(),
        'isUserLoggedIn' => is_user_logged_in(),
        'theme'          => get_option('infinity_theme_mode', 'dark-cosmic'),
        'stripeKey'      => get_option('infinity_stripe_publishable_key', ''),
    ));

    // Comment reply script
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }
}
add_action('wp_enqueue_scripts', 'infinity_enqueue_scripts');

/**
 * Register Custom Post Types
 */
function infinity_register_post_types() {
    // Simulations Post Type
    register_post_type('simulation', array(
        'labels' => array(
            'name'                  => esc_html__('Simulations', 'infinity'),
            'singular_name'         => esc_html__('Simulation', 'infinity'),
            'menu_name'             => esc_html__('Simulations', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Simulation', 'infinity'),
            'edit_item'             => esc_html__('Edit Simulation', 'infinity'),
            'new_item'              => esc_html__('New Simulation', 'infinity'),
            'view_item'             => esc_html__('View Simulation', 'infinity'),
            'search_items'          => esc_html__('Search Simulations', 'infinity'),
            'not_found'             => esc_html__('No simulations found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No simulations found in trash', 'infinity'),
            'all_items'             => esc_html__('All Simulations', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'simulation',
        'graphql_plural_name' => 'simulations',
        'menu_icon'           => 'dashicons-admin-site-alt3',
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt', 'author', 'comments'),
        'rewrite'             => array('slug' => 'simulations'),
        'capability_type'     => 'post',
    ));

    // Blueprints Post Type (User-created simulation configs)
    register_post_type('blueprint', array(
        'labels' => array(
            'name'                  => esc_html__('Blueprints', 'infinity'),
            'singular_name'         => esc_html__('Blueprint', 'infinity'),
            'menu_name'             => esc_html__('Blueprints', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Blueprint', 'infinity'),
            'edit_item'             => esc_html__('Edit Blueprint', 'infinity'),
            'new_item'              => esc_html__('New Blueprint', 'infinity'),
            'view_item'             => esc_html__('View Blueprint', 'infinity'),
            'search_items'          => esc_html__('Search Blueprints', 'infinity'),
            'not_found'             => esc_html__('No blueprints found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No blueprints found in trash', 'infinity'),
            'all_items'             => esc_html__('All Blueprints', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'blueprint',
        'graphql_plural_name' => 'blueprints',
        'menu_icon'           => 'dashicons-editor-code',
        'supports'            => array('title', 'editor', 'thumbnail', 'author', 'comments'),
        'rewrite'             => array('slug' => 'blueprints'),
        'capability_type'     => 'post',
    ));

    // Challenges Post Type
    register_post_type('challenge', array(
        'labels' => array(
            'name'                  => esc_html__('Challenges', 'infinity'),
            'singular_name'         => esc_html__('Challenge', 'infinity'),
            'menu_name'             => esc_html__('Challenges', 'infinity'),
            'add_new'               => esc_html__('Add New', 'infinity'),
            'add_new_item'          => esc_html__('Add New Challenge', 'infinity'),
            'edit_item'             => esc_html__('Edit Challenge', 'infinity'),
            'new_item'              => esc_html__('New Challenge', 'infinity'),
            'view_item'             => esc_html__('View Challenge', 'infinity'),
            'search_items'          => esc_html__('Search Challenges', 'infinity'),
            'not_found'             => esc_html__('No challenges found', 'infinity'),
            'not_found_in_trash'    => esc_html__('No challenges found in trash', 'infinity'),
            'all_items'             => esc_html__('All Challenges', 'infinity'),
        ),
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'challenge',
        'graphql_plural_name' => 'challenges',
        'menu_icon'           => 'dashicons-awards',
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite'             => array('slug' => 'challenges'),
        'capability_type'     => 'post',
    ));
}
add_action('init', 'infinity_register_post_types');

/**
 * Register Custom Taxonomies
 */
function infinity_register_taxonomies() {
    // Simulation Categories
    register_taxonomy('simulation_category', 'simulation', array(
        'labels' => array(
            'name'              => esc_html__('Simulation Categories', 'infinity'),
            'singular_name'     => esc_html__('Simulation Category', 'infinity'),
            'search_items'      => esc_html__('Search Categories', 'infinity'),
            'all_items'         => esc_html__('All Categories', 'infinity'),
            'edit_item'         => esc_html__('Edit Category', 'infinity'),
            'update_item'       => esc_html__('Update Category', 'infinity'),
            'add_new_item'      => esc_html__('Add New Category', 'infinity'),
            'new_item_name'     => esc_html__('New Category Name', 'infinity'),
            'menu_name'         => esc_html__('Categories', 'infinity'),
        ),
        'hierarchical'        => true,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'simulationCategory',
        'graphql_plural_name' => 'simulationCategories',
        'rewrite'             => array('slug' => 'simulation-category'),
    ));

    // Difficulty Level
    register_taxonomy('difficulty_level', array('simulation', 'challenge'), array(
        'labels' => array(
            'name'              => esc_html__('Difficulty Levels', 'infinity'),
            'singular_name'     => esc_html__('Difficulty Level', 'infinity'),
            'search_items'      => esc_html__('Search Levels', 'infinity'),
            'all_items'         => esc_html__('All Levels', 'infinity'),
            'edit_item'         => esc_html__('Edit Level', 'infinity'),
            'update_item'       => esc_html__('Update Level', 'infinity'),
            'add_new_item'      => esc_html__('Add New Level', 'infinity'),
            'new_item_name'     => esc_html__('New Level Name', 'infinity'),
            'menu_name'         => esc_html__('Difficulty', 'infinity'),
        ),
        'hierarchical'        => false,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'difficultyLevel',
        'graphql_plural_name' => 'difficultyLevels',
        'rewrite'             => array('slug' => 'difficulty'),
    ));

    // Physics Engine Tag
    register_taxonomy('physics_engine', 'simulation', array(
        'labels' => array(
            'name'              => esc_html__('Physics Engines', 'infinity'),
            'singular_name'     => esc_html__('Physics Engine', 'infinity'),
            'search_items'      => esc_html__('Search Engines', 'infinity'),
            'all_items'         => esc_html__('All Engines', 'infinity'),
            'edit_item'         => esc_html__('Edit Engine', 'infinity'),
            'update_item'       => esc_html__('Update Engine', 'infinity'),
            'add_new_item'      => esc_html__('Add New Engine', 'infinity'),
            'new_item_name'     => esc_html__('New Engine Name', 'infinity'),
            'menu_name'         => esc_html__('Physics Engines', 'infinity'),
        ),
        'hierarchical'        => false,
        'show_ui'             => true,
        'show_admin_column'   => true,
        'show_in_rest'        => true,
        'show_in_graphql'     => true,
        'graphql_single_name' => 'physicsEngine',
        'graphql_plural_name' => 'physicsEngines',
        'rewrite'             => array('slug' => 'physics-engine'),
    ));
}
add_action('init', 'infinity_register_taxonomies');

/**
 * Add Custom Image Sizes
 */
function infinity_custom_image_sizes() {
    add_image_size('simulation-thumbnail', 400, 300, true);
    add_image_size('simulation-hero', 1200, 600, true);
    add_image_size('blueprint-preview', 600, 400, true);
}
add_action('after_setup_theme', 'infinity_custom_image_sizes');

/**
 * Register Widget Areas
 */
function infinity_widgets_init() {
    register_sidebar(array(
        'name'          => esc_html__('Sidebar', 'infinity'),
        'id'            => 'sidebar-1',
        'description'   => esc_html__('Add widgets here to appear in your sidebar.', 'infinity'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h2 class="widget-title">',
        'after_title'   => '</h2>',
    ));

    register_sidebar(array(
        'name'          => esc_html__('Footer', 'infinity'),
        'id'            => 'footer-1',
        'description'   => esc_html__('Add widgets here to appear in your footer.', 'infinity'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h2 class="widget-title">',
        'after_title'   => '</h2>',
    ));
}
add_action('widgets_init', 'infinity_widgets_init');

/**
 * Add Theme Customizer Settings
 */
function infinity_customize_register($wp_customize) {
    // Theme Mode Section
    $wp_customize->add_section('infinity_theme_mode', array(
        'title'    => esc_html__('Theme Appearance', 'infinity'),
        'priority' => 30,
    ));

    $wp_customize->add_setting('infinity_theme_mode', array(
        'default'           => 'dark-cosmic',
        'sanitize_callback' => 'infinity_sanitize_theme_mode',
        'transport'         => 'refresh',
    ));

    $wp_customize->add_control('infinity_theme_mode', array(
        'label'   => esc_html__('Visual Theme', 'infinity'),
        'section' => 'infinity_theme_mode',
        'type'    => 'select',
        'choices' => array(
            'dark-cosmic'    => esc_html__('Dark Cosmic', 'infinity'),
            'light-playful'  => esc_html__('Light Playful', 'infinity'),
            'science-light'  => esc_html__('Science Mode (Light)', 'infinity'),
            'science-dark'   => esc_html__('Science Mode (Dark)', 'infinity'),
        ),
    ));

    // Stripe Settings Section
    $wp_customize->add_section('infinity_stripe_settings', array(
        'title'    => esc_html__('Subscription Settings', 'infinity'),
        'priority' => 40,
    ));

    $wp_customize->add_setting('infinity_stripe_publishable_key', array(
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ));

    $wp_customize->add_control('infinity_stripe_publishable_key', array(
        'label'       => esc_html__('Stripe Publishable Key', 'infinity'),
        'description' => esc_html__('Enter your Stripe publishable key for subscriptions', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'text',
    ));

    // Premium Pricing
    $wp_customize->add_setting('infinity_premium_price', array(
        'default'           => '20',
        'sanitize_callback' => 'absint',
    ));

    $wp_customize->add_control('infinity_premium_price', array(
        'label'       => esc_html__('Premium Monthly Price (USD)', 'infinity'),
        'section'     => 'infinity_stripe_settings',
        'type'        => 'number',
        'input_attrs' => array(
            'min'  => 1,
            'max'  => 1000,
            'step' => 1,
        ),
    ));
}
add_action('customize_register', 'infinity_customize_register');

/**
 * Sanitize theme mode setting
 */
function infinity_sanitize_theme_mode($input) {
    $valid_modes = array('dark-cosmic', 'light-playful', 'science-light', 'science-dark');
    return in_array($input, $valid_modes, true) ? $input : 'dark-cosmic';
}

/**
 * Add theme mode to body class
 */
function infinity_body_classes($classes) {
    $theme_mode = get_option('infinity_theme_mode', 'dark-cosmic');
    $classes[] = 'theme-' . $theme_mode;

    if (is_user_logged_in()) {
        $classes[] = 'user-logged-in';
    }

    return $classes;
}
add_filter('body_class', 'infinity_body_classes');

/**
 * Add theme mode data attribute to body
 */
function infinity_add_theme_attribute() {
    $theme_mode = get_option('infinity_theme_mode', 'dark-cosmic');
    echo ' data-theme="' . esc_attr($theme_mode) . '"';
}
add_action('body_open', 'infinity_add_theme_attribute');

/**
 * Include additional files
 */
require_once INFINITY_DIR . '/inc/user-roles.php';
require_once INFINITY_DIR . '/inc/subscription-functions.php';
require_once INFINITY_DIR . '/inc/simulation-meta.php';
require_once INFINITY_DIR . '/inc/api-endpoints.php';

// Load WooCommerce compatibility if plugin is active
if (class_exists('WooCommerce')) {
    require_once INFINITY_DIR . '/inc/woocommerce-integration.php';
}

// Load WPGraphQL extensions if plugin is active
if (function_exists('graphql')) {
    require_once INFINITY_DIR . '/inc/graphql-extensions.php';
}
